Project 7: Portfolio: Mobile Menu
V0pe/Portifolio pull request #8
Opened 2022-04-04 14:52 UTC by V0pe

### Project 7: Portfolio: Mobile Menu

In this project, I did the following:

- Update the mobile menu styles
- Add the javascript for menu opening and closing.

2022-04-04 20:01 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @V0pe and Team👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-04 20:01 UTC, thecodechaser commented on index.html
> +          <i class="fa fa-bars" id="menu"></i>
- [ ] Good job with the styles but for this project you are supposed to stick to the [Figma ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468)design as much as possible. Please use the correct size and color for your close(X) button, and make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/161621815-71ac539f-f963-45ff-8c30-bf9387a35291.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/161621847-239f10c6-7924-4261-aa89-66ed7a2939db.png)

2022-04-04 20:01 UTC, thecodechaser commented on index.html
>        <div class="header">
- [ ] Please make sure the mobile menu covers 100% of the window height. It will make your project looks more good and professional.

2022-04-05 07:13 UTC, V0pe commented on index.html
> +          <i class="fa fa-bars" id="menu"></i>
@thecodechaser Thanks for your insight. I have rectified the issue and attached is a picture. 
![image](https://user-images.githubusercontent.com/61356487/161698838-c6e17ac1-b900-4f73-8d77-944808393a0f.png)

2022-04-05 07:43 UTC, elmar8287 approved these changes
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-05 07:46 UTC, merged